/* Shared list controls. Filtering never changes the source collection or sale rules. */
const SlugBrowser=(()=>{
 const states=new Map();
 const cleanName=value=>Array.from(String(value??'').trim()).slice(0,32).join('');
 const name=s=>s?.nickname||s?.id||'';
 const htmlName=s=>name(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function setName(s,value){s.nickname=cleanName(value);if(typeof saveGame==='function')saveGame();}
 function rename(s,redraw){
  const d=document.createElement('dialog');d.style.cssText='width:min(360px,85vw);background:#193033;color:#efdfbd;border:1px solid #aa9564;border-radius:14px;padding:20px';
  d.innerHTML='<form><h3 style="margin-top:0">เปลี่ยนชื่อทาก</h3><label>ชื่อใหม่<input name="nickname" autocomplete="off" style="display:block;box-sizing:border-box;width:100%;margin:10px 0;padding:10px;background:#294043;color:#fff;border:1px solid #8d9b89;border-radius:6px"></label><p style="font-size:12px">ไม่เกิน 32 ตัวอักษร · ล้างชื่อเพื่อกลับไปใช้ชื่อเดิม</p><button type="submit">บันทึก</button> <button type="button" data-cancel>ยกเลิก</button></form>';
  document.body.append(d);const field=d.querySelector('input');field.value=s.nickname||'';
  d.addEventListener('keydown',e=>e.stopPropagation());d.addEventListener('close',()=>d.remove(),{once:true});d.querySelector('[data-cancel]').onclick=()=>d.close();
  d.querySelector('form').onsubmit=e=>{e.preventDefault();setName(s,field.value);d.close();redraw();};d.showModal();field.focus();field.select();
 }

 const state=key=>{if(!states.has(key))states.set(key,{liked:'all',values:'base',rules:[],sort:'original',gene:'vigor',target:50});return states.get(key);};
 function apply(list,key,get=x=>x){const f=state(key),value=s=>f.values==='current'?foodGenes(s):s.genes;
  const out=list.map((item,index)=>({item,index,s:get(item)})).filter(({s})=>{if(!s)return false;if(f.liked==='yes'&&!s.favorite||f.liked==='no'&&s.favorite)return false;const g=value(s);return f.rules.every(r=>{const v=Number(g[r.gene]);return Number.isFinite(v)&&(r.min===''||v>=Number(r.min))&&(r.max===''||v<=Number(r.max));});});
  if(f.sort!=='original')out.sort((a,b)=>{const av=Number(value(a.s)[f.gene]),bv=Number(value(b.s)[f.gene]);if(!Number.isFinite(av)||!Number.isFinite(bv))return Number.isFinite(av)?-1:Number.isFinite(bv)?1:a.index-b.index;const delta=f.sort==='near'||f.sort==='far'?Math.abs(av-Number(f.target))-Math.abs(bv-Number(f.target)):av-bv;return (f.sort==='desc'||f.sort==='far'?-delta:delta)||a.index-b.index;});return out.map(x=>x.item);
 }
 const css=document.createElement('style');css.textContent='.slugFilters{border:1px solid #718078;border-radius:9px;padding:9px;margin:9px 0;color:#dedecb;font-size:12px;background:#1b3033;grid-column:1/-1}.slugFilters summary{cursor:pointer}.slugFilterFields,.slugFilterRule{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.slugFilters label{display:flex!important;flex-direction:column;gap:4px}.slugFilters input{width:76px!important}.slugFilters select,.slugFilters input,.slugFilters button{font:inherit;color:#eee;background:#243d40;border:1px solid #677b72;border-radius:5px;padding:5px;max-width:100%}.slugFavorite{display:inline-flex;align-items:center;gap:4px;cursor:pointer;color:#c6bca8;padding:5px;border:1px solid #697b73;border-radius:7px;font-size:12px;vertical-align:middle}.slugFavorite[aria-pressed=true]{color:#ffa7bd;background:#643b4855}.slugFavorite svg{width:18px;height:18px;pointer-events:none}.slugFilterEmpty{font-size:12px;color:#d3bd92;padding:8px}';document.head.append(css);
 function heart(host,s,redraw=()=>{},key){if(!s)return;const b=document.createElement('span');b.className='slugFavorite';b.setAttribute('role','button');b.tabIndex=0;b._slug=s;const paint=()=>{b.setAttribute('aria-pressed',String(!!s.favorite));b.setAttribute('aria-label',(s.favorite?'เลิกถูกใจ ':'ถูกใจ ')+s.id);b.innerHTML='<svg viewBox="0 0 24 24" fill="'+(s.favorite?'currentColor':'none')+'" stroke="currentColor" stroke-width="1.7"><path d="M12 21S2 15 2 8a5 5 0 0 1 10-2 5 5 0 0 1 10 2c0 7-10 13-10 13Z"/></svg>'+(s.favorite?'ถูกใจแล้ว':'ถูกใจ');};paint();const toggle=e=>{e.preventDefault();e.stopPropagation();s.favorite=!s.favorite;if(typeof saveGame==='function')saveGame();for(const other of document.querySelectorAll('.slugFavorite'))if(other._slug===s){other.setAttribute('aria-pressed',String(s.favorite));other.setAttribute('aria-label',(s.favorite?'เลิกถูกใจ ':'ถูกใจ ')+s.id);other.querySelector('svg').setAttribute('fill',s.favorite?'currentColor':'none');}paint();redraw();};b.onclick=toggle;b.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')toggle(e);};b.onpointerdown=e=>e.stopPropagation();host.append(b);host.querySelector('.slugRename')?.remove();const edit=document.createElement('span');edit.className='slugRename slugFavorite';edit.setAttribute('role','button');edit.tabIndex=0;edit.textContent='เปลี่ยนชื่อ';edit.setAttribute('aria-label','เปลี่ยนชื่อ '+name(s));edit.onclick=e=>{e.preventDefault();e.stopPropagation();rename(s,redraw);};edit.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();rename(s,redraw);}};edit.onpointerdown=e=>e.stopPropagation();host.append(edit);if(key){const f=state(key),keys=[...new Set([...(f.sort!=='original'?[f.gene]:[]),...f.rules.map(r=>r.gene)])];if(keys.length){const note=document.createElement('small'),g=f.values==='current'?foodGenes(s):s.genes;note.style.cssText='display:block;color:#d8c48e;font-size:11px;margin-top:5px';note.textContent=keys.map(k=>(SlugEngine.GENES.find(x=>x.k===k)?.th||k)+' '+g[k]).join(' · ')+(f.sort==='near'||f.sort==='far'?' · ห่างเป้าหมาย '+Math.abs(Number(g[f.gene])-Number(f.target)):'');host.append(note);}}return b;}
 function mount(host,key,redraw){const existing=[...host.children].find(x=>x.dataset?.slugFilters===key);if(existing)return existing;const f=state(key),d=document.createElement('details');d.className='slugFilters';d.dataset.slugFilters=key;d.open=!!f.open;const summary=document.createElement('summary');summary.textContent='กรอง / เรียงทาก'+(f.liked!=='all'||f.rules.length||f.sort!=='original'?' · ใช้งานอยู่':'');d.append(summary);const repaint=()=>{d.remove();redraw();};d.ontoggle=()=>f.open=d.open;const fields=document.createElement('div');fields.className='slugFilterFields';d.append(fields);
  const select=(parent,label,options,value,change)=>{const l=document.createElement('label');l.textContent=label;const e=document.createElement('select');for(const [v,t]of options){const o=document.createElement('option');o.value=v;o.textContent=t;e.append(o);}e.value=value;e.onchange=()=>{change(e.value);repaint();};l.append(e);parent.append(l);return e;};
  const number=(parent,label,value,change)=>{const l=document.createElement('label');l.textContent=label;const e=document.createElement('input');e.type='number';e.step='any';e.value=value;e.onchange=()=>{if(e.value!==''&&!Number.isFinite(Number(e.value)))return;change(e.value);repaint();};l.append(e);parent.append(l);};
  const geneOptions=SlugEngine.GENES.map(g=>[g.k,g.th]);
  select(fields,'ถูกใจ',[['all','ทั้งหมด'],['yes','เฉพาะที่ถูกใจ'],['no','ยังไม่ถูกใจ']],f.liked,v=>f.liked=v);
  select(fields,'ค่าที่ใช้',[['base','ยีนกำเนิด'],['current','รวมบัฟอาหาร']],f.values,v=>f.values=v);
  select(fields,'เรียง',[['original','ลำดับเดิม'],['near','ใกล้เป้าหมายก่อน'],['far','ห่างเป้าหมายก่อน'],['asc','ค่าต่ำไปสูง'],['desc','ค่าสูงไปต่ำ']],f.sort,v=>f.sort=v);
  select(fields,'ยีนที่เรียง',geneOptions,f.gene,v=>f.gene=v);number(fields,'ค่าเป้าหมาย',f.target,v=>f.target=v===''?0:Number(v));
  f.rules.forEach((r,i)=>{const row=document.createElement('div');row.className='slugFilterRule';select(row,'ยีน',geneOptions,r.gene,v=>r.gene=v);number(row,'ต่ำสุด',r.min,v=>r.min=v);number(row,'สูงสุด',r.max,v=>r.max=v);const del=document.createElement('button');del.type='button';del.textContent='ลบ';del.onclick=()=>{f.rules.splice(i,1);repaint();};row.append(del);d.append(row);});
  const add=document.createElement('button');add.type='button';add.textContent='เพิ่มเงื่อนไขยีน';add.onclick=()=>{f.rules.push({gene:'vigor',min:'',max:''});f.open=true;repaint();};d.append(add);const reset=document.createElement('button');reset.type='button';reset.textContent='ล้างตัวกรอง';reset.onclick=()=>{states.delete(key);repaint();};d.append(reset);host.prepend(d);return d;
 }
 function remount(host,key,redraw){for(const child of [...host.children])if(child.dataset?.slugFilters===key)child.remove();return mount(host,key,redraw);}
 return {apply,state,mount,remount,heart,name,htmlName,cleanName,setName,rename};
})();
