import fs from 'node:fs';
const destination=new URL('./Custom.html',import.meta.url);
let html=fs.readFileSync(destination,'utf8');
const start=html.indexOf('<script>\nconst OREO_PACK=');
if(start<0)throw Error('Expected workspace editor with embedded Oreo pack');
html=html.slice(0,start);
if(!html.includes('surface:validSurface(e.surface)'))html=html.replace('animationKeys:validKeys(e.animationKeys)});','animationKeys:validKeys(e.animationKeys), surface:validSurface(e.surface)});');
if(!html.includes('doc.libraryFavorites=validLibrary(o.library)'))html=html.replace('stopAnimation(); doc.animation=validAnimation(o.animation); animationTime=0;','stopAnimation(); doc.animation=validAnimation(o.animation); animationTime=0; doc.libraryFavorites=validLibrary(o.library);');
const pack=[['oreo_body_white','Oreo · ลำตัวขาว','body-white-v1.png',330,false],['oreo_horn_white','Oreo · หนวดขาว','rhinophore-white-v1.png',100,true],['oreo_gill_white','Oreo · เหงือกขาว (ร่าง)','gill-white-v1.png',170,true]].map(([key,name,file,height,stalk])=>{const b=fs.readFileSync(new URL('../../assets/oreo2d/'+file,import.meta.url));return {key,name,height,stalk,w:b.readUInt32BE(16),h:b.readUInt32BE(20),src:'data:image/png;base64,'+b.toString('base64')}});
html+='<script>\nconst OREO_PACK='+JSON.stringify(pack)+';\n'+['custom-features.js','bone-features.js','animation-features.js','library-features.js','shortcut-features.js','surface-features.js','transform-shortcuts.js'].map(f=>fs.readFileSync(new URL('./'+f,import.meta.url),'utf8')).join('\n')+'\n</script>\n</body>\n</html>';
fs.writeFileSync(new URL('./Custom.html',import.meta.url),html);
